### ISSUE TITLE
FE012 - OCR Testing

### ISSUE THREAD

**Issue by keithching** [tangoatsumare/tangoatsumare-frontend#12]
## Assumptions
- Use a photo that contains texts on it that has been stored in the frontend client (smart phone or web browser)

## Tasks
- create a Google Vision API account
https://cloud.google.com/vision/docs/setup
https://cloud.google.com/vision/docs/before-you-begin

- setting up environment variables for the SECRET cloud vision JSON file
https://medium.com/swlh/how-to-properly-use-environment-variables-in-an-expo-react-native-app-7ab852590b30

- gcloud CLI
https://cloud.google.com/sdk/docs/cheatsheet

- installing Google Vision client libraries
https://cloud.google.com/vision/docs/libraries#client-libraries-install-nodejs
OR
- Cloud Vision REST API
https://cloud.google.com/vision/docs/reference/rest

- with React Native Expo
  - [x] create a blank screen
  - [x] put a photo in there
  - [x] create a button to send a HTTP request to the Vision API (with that photo)
REST API endpoint documentation
https://cloud.google.com/vision/docs/reference/rest/v1/images/annotate
https://cloud.google.com/vision/docs/reference/rest/v1/Feature
https://cloud.google.com/vision/docs/reference/rest/v1/AnnotateImageRequest

  - [x] get the response from the API
  - [x] display the response data on the Screen
  - [x] implement text selection:
     - if a word/phrase is highlighted, grab that word and set state
     - display that word on another div (like a preview div)
  - [x] as the word gets selected, add a button that says look up dictionary
  - [ ] when the dictionary lookup is done, some response should gets send back and show on the screen
  - [ ] when the fields of word selection, dictionary lookup definition are filled, show a button that lets the user submit a flashcard
  - [ ] console log the whole flashcard. connects with the **backend team on Flashcard**
  - [ ] connects with the **frontend team on Camera**
  - [ ] connects with the **backend team on Firebase Cloud Storage**
