### ISSUE TITLE
FE033 - SRS Review Page

### ISSUE THREAD

**Issue by keithching** [tangoatsumare/tangoatsumare-frontend#33]
## Tasks 
- [x] do a wireframe for how the workflow goes (refer to Miro)
   - [x] how many screens we need?
   - [x] what data / props / states we need?
      - who the current user is
      - user settings for SRS, or other stuff
      - a set of modified flashcards with timing property (card ready for review)
      - review stack: a daily array []. push and pop
   - [x] how to persist the data in the database?
     - we might want to consider using relational data to minimize duplications
 
## Components regarding flashcard creation
1. The core flashcard part
2. The SRS part (make it into a reusable component)

## Algorithm
- [x] figure out what data is needed
- [x] implement supermemo. test it out via the terminal
supermemo function implementation refer to https://github.com/Maxvien/supermemo/blob/master/src/supermemo.ts

### Assumption
1. to simplify the 0-5 grade scale system, adopt only either OK or not OK for the grade.

Original grade scale in the SM2 algorithm:
5 - perfect response
4 - correct response after a hesitation
3 - correct response recalled with serious difficulty
2 - incorrect response; where the correct one seemed easy to recall
1 - incorrect response; the correct one remembered
0 - complete blackout.

Simplified version for our implementation:
[make it into a variable that is tweakable] OK : a score of 5
[make it into a variable that is tweakable] NOT OK: a score of 1

remark according to the doc: 
for score < 3, start the flashcard brand new (repetition back to 0)

## Frontend
- [x] create a screen for review homepage
- [x] implement the frontend UI
- [ ] implement my SRS cards status screen
   - [ ] show status (new? due?)
   - [ ] review history
   - [ ] ready for review?
- [ ] implement CRUD for my SRS cards
- [ ] notification when review is ready?

## Backend
- [x] implement the **backend API endpoints**
- [ ] CRUD endpoints

### Internal setting (expose / not expose)
- Limit of new cards for study purpose per day (to be reviewed)
- Get right into the review algorithm (basic)
- Implement steps for new cards (advanced)
- Include a setting that says: convert flashcard into review-able flashcard by default

### Resources
https://github.com/Maxvien/supermemo
